# rating categories
INSERT INTO `rating_categories`(`id`, `name`, `description`, `order`) VALUES (1,'Environment','How is workplace environment?',1);
INSERT INTO `rating_categories`(`id`, `name`, `description`, `order`) VALUES (2,'Employee/Mentor','Was they helpful/Kind?',2);
INSERT INTO `rating_categories`(`id`, `name`, `description`, `order`) VALUES (3,'Task/Research', 'Was the task interesting?',3);
INSERT INTO `rating_categories`(`id`, `name`, `description`, `order`) VALUES (4,'Transportation','Was it easy to get to work?',4);
INSERT INTO `rating_categories`(`id`, `name`, `description`, `order`) VALUES (5,'Educational Benefits','Did your skill improve?',5);
INSERT INTO `rating_categories`(`id`, `name`, `description`, `order`) VALUES (6,'Overall','Overall satification?',6);

# tag_ctegories
INSERT INTO `tag_categories`(`id`, `name`, `order`) VALUES (1,'Paid',1);
INSERT INTO `tag_categories`(`id`, `name`, `order`) VALUES (2,'Working hours',2);
INSERT INTO `tag_categories`(`id`, `name`, `order`) VALUES (3,'Type of work',3);
INSERT INTO `tag_categories`(`id`, `name`, `order`) VALUES (4,'Programming language',4);
INSERT INTO `tag_categories`(`id`, `name`, `order`) VALUES (5,'Field of work',5);

# tags
	# Paid
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (1,1,'Non-Paid');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (2,1,'Paid');
	# Working Hours
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (3,2,'Fix');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (4,2,'Flexible');
	# Type of work
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (5,3,'Research');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (6,3,'Project');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (7,3,'It support');
	# Programming language
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (8,4,'Assembly');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (9,4,'C');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (10,4,'C#');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (11,4,'C++');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (12,4,'CSS');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (13,4,'HTML');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (14,4,'Java');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (15,4,'JavaScript');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (16,4,'Objective-C');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (17,4,'PHP');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (18,4,'Python');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (19,4,'Ruby');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (20,4,'SQL');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (21,4,'Swift');
	# field of work
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (22,5,'Artificial Intelligence');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (23,5,'Business Analyst');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (24,5,'Business Intelligence');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (25,5,'Computer Security');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (26,5,'Database Design');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (27,5,'Desktop App Dev');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (28,5,'Game Development');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (29,5,'Graphic Design');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (30,5,'Image Processing');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (31,5,'Mobile Dev - Andriod');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (32,5,'Mobile Dev - iOS');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (33,5,'Networking / System Admin');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (34,5,'Quality Assurance / Testing');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (35,5,'Technical Writing');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (36,5,'Web Development');
INSERT INTO `tags`(`id`, `tag_category_id`, `value`) VALUES (37,5,'Webmaster / Web Design');



INSERT INTO `countries`(`name`) VALUES ('Afghanistan');
INSERT INTO `countries`(`name`) VALUES ('�land Islands');
INSERT INTO `countries`(`name`) VALUES ('Albania');
INSERT INTO `countries`(`name`) VALUES ('Algeria');
INSERT INTO `countries`(`name`) VALUES ('American Samoa');
INSERT INTO `countries`(`name`) VALUES ('Andorra');
INSERT INTO `countries`(`name`) VALUES ('Angola');
INSERT INTO `countries`(`name`) VALUES ('Anguilla');
INSERT INTO `countries`(`name`) VALUES ('Antarctica');
INSERT INTO `countries`(`name`) VALUES ('Antigua and Barbuda');
INSERT INTO `countries`(`name`) VALUES ('Argentina');
INSERT INTO `countries`(`name`) VALUES ('Armenia');
INSERT INTO `countries`(`name`) VALUES ('Aruba');
INSERT INTO `countries`(`name`) VALUES ('Australia');
INSERT INTO `countries`(`name`) VALUES ('Austria');
INSERT INTO `countries`(`name`) VALUES ('Azerbaijan');
INSERT INTO `countries`(`name`) VALUES ('Bahamas');
INSERT INTO `countries`(`name`) VALUES ('Bahrain');
INSERT INTO `countries`(`name`) VALUES ('Bangladesh');
INSERT INTO `countries`(`name`) VALUES ('Barbados');
INSERT INTO `countries`(`name`) VALUES ('Belarus');
INSERT INTO `countries`(`name`) VALUES ('Belgium');
INSERT INTO `countries`(`name`) VALUES ('Belize');
INSERT INTO `countries`(`name`) VALUES ('Benin');
INSERT INTO `countries`(`name`) VALUES ('Bermuda');
INSERT INTO `countries`(`name`) VALUES ('Bhutan');
INSERT INTO `countries`(`name`) VALUES ('Bolivia');
INSERT INTO `countries`(`name`) VALUES ('Bosnia and Herzegovina');
INSERT INTO `countries`(`name`) VALUES ('Botswana');
INSERT INTO `countries`(`name`) VALUES ('Bouvet Island');
INSERT INTO `countries`(`name`) VALUES ('Brazil');
INSERT INTO `countries`(`name`) VALUES ('British Indian Ocean Territory');
INSERT INTO `countries`(`name`) VALUES ('Brunei Darussalam');
INSERT INTO `countries`(`name`) VALUES ('Bulgaria');
INSERT INTO `countries`(`name`) VALUES ('Burkina Faso');
INSERT INTO `countries`(`name`) VALUES ('Burundi');
INSERT INTO `countries`(`name`) VALUES ('Cambodia');
INSERT INTO `countries`(`name`) VALUES ('Cameroon');
INSERT INTO `countries`(`name`) VALUES ('Canada');
INSERT INTO `countries`(`name`) VALUES ('Cape Verde');
INSERT INTO `countries`(`name`) VALUES ('Cayman Islands');
INSERT INTO `countries`(`name`) VALUES ('Central African Republic');
INSERT INTO `countries`(`name`) VALUES ('Chad');
INSERT INTO `countries`(`name`) VALUES ('Chile');
INSERT INTO `countries`(`name`) VALUES ('China');
INSERT INTO `countries`(`name`) VALUES ('Christmas Island');
INSERT INTO `countries`(`name`) VALUES ('Cocos (Keeling) Islands');
INSERT INTO `countries`(`name`) VALUES ('Colombia');
INSERT INTO `countries`(`name`) VALUES ('Comoros');
INSERT INTO `countries`(`name`) VALUES ('Congo');
INSERT INTO `countries`(`name`) VALUES ('Congo, The Democratic Republic of The');
INSERT INTO `countries`(`name`) VALUES ('Cook Islands');
INSERT INTO `countries`(`name`) VALUES ('Costa Rica');
INSERT INTO `countries`(`name`) VALUES ('Cote D\'ivoire');
INSERT INTO `countries`(`name`) VALUES ('Croatia');
INSERT INTO `countries`(`name`) VALUES ('Cuba');
INSERT INTO `countries`(`name`) VALUES ('Cyprus');
INSERT INTO `countries`(`name`) VALUES ('Czech Republic');
INSERT INTO `countries`(`name`) VALUES ('Denmark');
INSERT INTO `countries`(`name`) VALUES ('Djibouti');
INSERT INTO `countries`(`name`) VALUES ('Dominica');
INSERT INTO `countries`(`name`) VALUES ('Dominican Republic');
INSERT INTO `countries`(`name`) VALUES ('Ecuador');
INSERT INTO `countries`(`name`) VALUES ('Egypt');
INSERT INTO `countries`(`name`) VALUES ('El Salvador');
INSERT INTO `countries`(`name`) VALUES ('Equatorial Guinea');
INSERT INTO `countries`(`name`) VALUES ('Eritrea');
INSERT INTO `countries`(`name`) VALUES ('Estonia');
INSERT INTO `countries`(`name`) VALUES ('Ethiopia');
INSERT INTO `countries`(`name`) VALUES ('Falkland Islands (Malvinas)');
INSERT INTO `countries`(`name`) VALUES ('Faroe Islands');
INSERT INTO `countries`(`name`) VALUES ('Fiji');
INSERT INTO `countries`(`name`) VALUES ('Finland');
INSERT INTO `countries`(`name`) VALUES ('France');
INSERT INTO `countries`(`name`) VALUES ('French Guiana');
INSERT INTO `countries`(`name`) VALUES ('French Polynesia');
INSERT INTO `countries`(`name`) VALUES ('French Southern Territories');
INSERT INTO `countries`(`name`) VALUES ('Gabon');
INSERT INTO `countries`(`name`) VALUES ('Gambia');
INSERT INTO `countries`(`name`) VALUES ('Georgia');
INSERT INTO `countries`(`name`) VALUES ('Germany');
INSERT INTO `countries`(`name`) VALUES ('Ghana');
INSERT INTO `countries`(`name`) VALUES ('Gibraltar');
INSERT INTO `countries`(`name`) VALUES ('Greece');
INSERT INTO `countries`(`name`) VALUES ('Greenland');
INSERT INTO `countries`(`name`) VALUES ('Grenada');
INSERT INTO `countries`(`name`) VALUES ('Guadeloupe');
INSERT INTO `countries`(`name`) VALUES ('Guam');
INSERT INTO `countries`(`name`) VALUES ('Guatemala');
INSERT INTO `countries`(`name`) VALUES ('Guernsey');
INSERT INTO `countries`(`name`) VALUES ('Guinea');
INSERT INTO `countries`(`name`) VALUES ('Guinea-bissau');
INSERT INTO `countries`(`name`) VALUES ('Guyana');
INSERT INTO `countries`(`name`) VALUES ('Haiti');
INSERT INTO `countries`(`name`) VALUES ('Heard Island and Mcdonald Islands');
INSERT INTO `countries`(`name`) VALUES ('Holy See (Vatican City State)');
INSERT INTO `countries`(`name`) VALUES ('Honduras');
INSERT INTO `countries`(`name`) VALUES ('Hong Kong');
INSERT INTO `countries`(`name`) VALUES ('Hungary');
INSERT INTO `countries`(`name`) VALUES ('Iceland');
INSERT INTO `countries`(`name`) VALUES ('India');
INSERT INTO `countries`(`name`) VALUES ('Indonesia');
INSERT INTO `countries`(`name`) VALUES ('Iran, Islamic Republic of');
INSERT INTO `countries`(`name`) VALUES ('Iraq');
INSERT INTO `countries`(`name`) VALUES ('Ireland');
INSERT INTO `countries`(`name`) VALUES ('Isle of Man');
INSERT INTO `countries`(`name`) VALUES ('Israel');
INSERT INTO `countries`(`name`) VALUES ('Italy');
INSERT INTO `countries`(`name`) VALUES ('Jamaica');
INSERT INTO `countries`(`name`) VALUES ('Japan');
INSERT INTO `countries`(`name`) VALUES ('Jersey');
INSERT INTO `countries`(`name`) VALUES ('Jordan');
INSERT INTO `countries`(`name`) VALUES ('Kazakhstan');
INSERT INTO `countries`(`name`) VALUES ('Kenya');
INSERT INTO `countries`(`name`) VALUES ('Kiribati');
INSERT INTO `countries`(`name`) VALUES ('Korea, Democratic People\'s Republic of');
INSERT INTO `countries`(`name`) VALUES ('Korea, Republic of');
INSERT INTO `countries`(`name`) VALUES ('Kuwait');
INSERT INTO `countries`(`name`) VALUES ('Kyrgyzstan');
INSERT INTO `countries`(`name`) VALUES ('Lao People\'s Democratic Republic');
INSERT INTO `countries`(`name`) VALUES ('Latvia');
INSERT INTO `countries`(`name`) VALUES ('Lebanon');
INSERT INTO `countries`(`name`) VALUES ('Lesotho');
INSERT INTO `countries`(`name`) VALUES ('Liberia');
INSERT INTO `countries`(`name`) VALUES ('Libyan Arab Jamahiriya');
INSERT INTO `countries`(`name`) VALUES ('Liechtenstein');
INSERT INTO `countries`(`name`) VALUES ('Lithuania');
INSERT INTO `countries`(`name`) VALUES ('Luxembourg');
INSERT INTO `countries`(`name`) VALUES ('Macao');
INSERT INTO `countries`(`name`) VALUES ('Macedonia, The Former Yugoslav Republic of');
INSERT INTO `countries`(`name`) VALUES ('Madagascar');
INSERT INTO `countries`(`name`) VALUES ('Malawi');
INSERT INTO `countries`(`name`) VALUES ('Malaysia');
INSERT INTO `countries`(`name`) VALUES ('Maldives');
INSERT INTO `countries`(`name`) VALUES ('Mali');
INSERT INTO `countries`(`name`) VALUES ('Malta');
INSERT INTO `countries`(`name`) VALUES ('Marshall Islands');
INSERT INTO `countries`(`name`) VALUES ('Martinique');
INSERT INTO `countries`(`name`) VALUES ('Mauritania');
INSERT INTO `countries`(`name`) VALUES ('Mauritius');
INSERT INTO `countries`(`name`) VALUES ('Mayotte');
INSERT INTO `countries`(`name`) VALUES ('Mexico');
INSERT INTO `countries`(`name`) VALUES ('Micronesia, Federated States of');
INSERT INTO `countries`(`name`) VALUES ('Moldova, Republic of');
INSERT INTO `countries`(`name`) VALUES ('Monaco');
INSERT INTO `countries`(`name`) VALUES ('Mongolia');
INSERT INTO `countries`(`name`) VALUES ('Montenegro');
INSERT INTO `countries`(`name`) VALUES ('Montserrat');
INSERT INTO `countries`(`name`) VALUES ('Morocco');
INSERT INTO `countries`(`name`) VALUES ('Mozambique');
INSERT INTO `countries`(`name`) VALUES ('Myanmar');
INSERT INTO `countries`(`name`) VALUES ('Namibia');
INSERT INTO `countries`(`name`) VALUES ('Nauru');
INSERT INTO `countries`(`name`) VALUES ('Nepal');
INSERT INTO `countries`(`name`) VALUES ('Netherlands');
INSERT INTO `countries`(`name`) VALUES ('Netherlands Antilles');
INSERT INTO `countries`(`name`) VALUES ('New Caledonia');
INSERT INTO `countries`(`name`) VALUES ('New Zealand');
INSERT INTO `countries`(`name`) VALUES ('Nicaragua');
INSERT INTO `countries`(`name`) VALUES ('Niger');
INSERT INTO `countries`(`name`) VALUES ('Nigeria');
INSERT INTO `countries`(`name`) VALUES ('Niue');
INSERT INTO `countries`(`name`) VALUES ('Norfolk Island');
INSERT INTO `countries`(`name`) VALUES ('Northern Mariana Islands');
INSERT INTO `countries`(`name`) VALUES ('Norway');
INSERT INTO `countries`(`name`) VALUES ('Oman');
INSERT INTO `countries`(`name`) VALUES ('Pakistan');
INSERT INTO `countries`(`name`) VALUES ('Palau');
INSERT INTO `countries`(`name`) VALUES ('Palestinian Territory, Occupied');
INSERT INTO `countries`(`name`) VALUES ('Panama');
INSERT INTO `countries`(`name`) VALUES ('Papua New Guinea');
INSERT INTO `countries`(`name`) VALUES ('Paraguay');
INSERT INTO `countries`(`name`) VALUES ('Peru');
INSERT INTO `countries`(`name`) VALUES ('Philippines');
INSERT INTO `countries`(`name`) VALUES ('Pitcairn');
INSERT INTO `countries`(`name`) VALUES ('Poland');
INSERT INTO `countries`(`name`) VALUES ('Portugal');
INSERT INTO `countries`(`name`) VALUES ('Puerto Rico');
INSERT INTO `countries`(`name`) VALUES ('Qatar');
INSERT INTO `countries`(`name`) VALUES ('Reunion');
INSERT INTO `countries`(`name`) VALUES ('Romania');
INSERT INTO `countries`(`name`) VALUES ('Russian Federation');
INSERT INTO `countries`(`name`) VALUES ('Rwanda');
INSERT INTO `countries`(`name`) VALUES ('Saint Helena');
INSERT INTO `countries`(`name`) VALUES ('Saint Kitts and Nevis');
INSERT INTO `countries`(`name`) VALUES ('Saint Lucia');
INSERT INTO `countries`(`name`) VALUES ('Saint Pierre and Miquelon');
INSERT INTO `countries`(`name`) VALUES ('Saint Vincent and The Grenadines');
INSERT INTO `countries`(`name`) VALUES ('Samoa');
INSERT INTO `countries`(`name`) VALUES ('San Marino');
INSERT INTO `countries`(`name`) VALUES ('Sao Tome and Principe');
INSERT INTO `countries`(`name`) VALUES ('Saudi Arabia');
INSERT INTO `countries`(`name`) VALUES ('Senegal');
INSERT INTO `countries`(`name`) VALUES ('Serbia');
INSERT INTO `countries`(`name`) VALUES ('Seychelles');
INSERT INTO `countries`(`name`) VALUES ('Sierra Leone');
INSERT INTO `countries`(`name`) VALUES ('Singapore');
INSERT INTO `countries`(`name`) VALUES ('Slovakia');
INSERT INTO `countries`(`name`) VALUES ('Slovenia');
INSERT INTO `countries`(`name`) VALUES ('Solomon Islands');
INSERT INTO `countries`(`name`) VALUES ('Somalia');
INSERT INTO `countries`(`name`) VALUES ('South Africa');
INSERT INTO `countries`(`name`) VALUES ('South Georgia and The South Sandwich Islands');
INSERT INTO `countries`(`name`) VALUES ('Spain');
INSERT INTO `countries`(`name`) VALUES ('Sri Lanka');
INSERT INTO `countries`(`name`) VALUES ('Sudan');
INSERT INTO `countries`(`name`) VALUES ('Suriname');
INSERT INTO `countries`(`name`) VALUES ('Svalbard and Jan Mayen');
INSERT INTO `countries`(`name`) VALUES ('Swaziland');
INSERT INTO `countries`(`name`) VALUES ('Sweden');
INSERT INTO `countries`(`name`) VALUES ('Switzerland');
INSERT INTO `countries`(`name`) VALUES ('Syrian Arab Republic');
INSERT INTO `countries`(`name`) VALUES ('Taiwan, Province of China');
INSERT INTO `countries`(`name`) VALUES ('Tajikistan');
INSERT INTO `countries`(`name`) VALUES ('Tanzania, United Republic of');
INSERT INTO `countries`(`name`) VALUES ('Thailand');
INSERT INTO `countries`(`name`) VALUES ('Timor-leste');
INSERT INTO `countries`(`name`) VALUES ('Togo');
INSERT INTO `countries`(`name`) VALUES ('Tokelau');
INSERT INTO `countries`(`name`) VALUES ('Tonga');
INSERT INTO `countries`(`name`) VALUES ('Trinidad and Tobago');
INSERT INTO `countries`(`name`) VALUES ('Tunisia');
INSERT INTO `countries`(`name`) VALUES ('Turkey');
INSERT INTO `countries`(`name`) VALUES ('Turkmenistan');
INSERT INTO `countries`(`name`) VALUES ('Turks and Caicos Islands');
INSERT INTO `countries`(`name`) VALUES ('Tuvalu');
INSERT INTO `countries`(`name`) VALUES ('Uganda');
INSERT INTO `countries`(`name`) VALUES ('Ukraine');
INSERT INTO `countries`(`name`) VALUES ('United Arab Emirates');
INSERT INTO `countries`(`name`) VALUES ('United Kingdom');
INSERT INTO `countries`(`name`) VALUES ('United States');
INSERT INTO `countries`(`name`) VALUES ('United States Minor Outlying Islands');
INSERT INTO `countries`(`name`) VALUES ('Uruguay');
INSERT INTO `countries`(`name`) VALUES ('Uzbekistan');
INSERT INTO `countries`(`name`) VALUES ('Vanuatu');
INSERT INTO `countries`(`name`) VALUES ('Venezuela');
INSERT INTO `countries`(`name`) VALUES ('Viet Nam');
INSERT INTO `countries`(`name`) VALUES ('Virgin Islands, British');
INSERT INTO `countries`(`name`) VALUES ('Virgin Islands, U.S.');
INSERT INTO `countries`(`name`) VALUES ('Wallis and Futuna');
INSERT INTO `countries`(`name`) VALUES ('Western Sahara');
INSERT INTO `countries`(`name`) VALUES ('Yemen');
INSERT INTO `countries`(`name`) VALUES ('Zambia');
INSERT INTO `countries`(`name`) VALUES ('Zimbabwe');



INSERT INTO `students` (`id` ,`student_id` ,`name` ,`nickname` ,`contact_url` ,`file_id` ,`is_admin`)VALUES ('1',  '5410546041',  'CHA KHA',  'ANTISEC',  'adsfkjalsdhfalksd',  '15',  '1');
INSERT INTO `legacy`.`places` (`id`, `name`, `full_name`, `address`, `country_id`, `latitude`, `longitude`, `about`, `website_url`, `file_id`) VALUES ('1', 'Orion', 'Orion Health', 'Addresss', '23', '1.000000', '1.000000', 'about orion', 'http://www.google.com', '15');

